FROM node:16.4.2-alpine
WORKDIR /usr/src/app

# Installs package to serve the frontend
RUN npm install -g serve

COPY package.json package-lock.json ./
RUN npm ci

COPY . ./
RUN npm run build:app


CMD ["serve", "-s", "build"]
