---
variables:
  REVIEW_APPS_DOMAIN: 'wip.aerolab.co'
  REVIEW_APPS_SUBDOMAIN_PREFIX: 'datagenero-desktop'

.functions: &functions |
  [[ "$TRACE" ]] && set -x

  function persist_environment_url() {
    echo $CI_ENVIRONMENT_URL > environment_url.txt
  }

.dokku: &dokku
  before_script:
    - *functions
    - mkdir -p ~/.ssh
    - echo "$DOKKU_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $REVIEW_APPS_DOMAIN >> ~/.ssh/known_hosts
  image: ilyasemenov/gitlab-ci-git-push

stages:
  - review
  - cleanup

# REVIEW BRANCHES
review:
  <<: *dokku
  stage: review
  script:
    - export REVIEW_APP="$REVIEW_APPS_SUBDOMAIN_PREFIX-$CI_ENVIRONMENT_SLUG"
    - ssh dokku@$REVIEW_APPS_DOMAIN apps:create $REVIEW_APP 2> /dev/null || echo "App already exists"
    - ssh dokku@$REVIEW_APPS_DOMAIN certs:add $REVIEW_APP /home/dokku/.https/server.crt /home/dokku/.https/server.key
    - ssh dokku@$REVIEW_APPS_DOMAIN config:set $REVIEW_APP NODE_ENV=production
    - ssh dokku@$REVIEW_APPS_DOMAIN docker-options:add $REVIEW_APP build "--build-arg NODE_ENV=production"
    - git push dokku@$REVIEW_APPS_DOMAIN:$REVIEW_APP HEAD:refs/heads/main --force
    - echo $CI_ENVIRONMENT_URL > environment_url.txt
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$REVIEW_APPS_SUBDOMAIN_PREFIX-$CI_ENVIRONMENT_SLUG.$REVIEW_APPS_DOMAIN
    on_stop: stop review
  artifacts:
    paths: [environment_url.txt]
  only:
    refs:
      - branches
  except:
    refs:
      - main
      - develop
    variables:
      - $REVIEW_DISABLED

stop review:
  <<: *dokku
  stage: cleanup
  variables:
    GIT_STRATEGY: none
  script:
    - ssh dokku@$REVIEW_APPS_DOMAIN apps:destroy $REVIEW_APPS_SUBDOMAIN_PREFIX-$CI_ENVIRONMENT_SLUG --force
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  when: manual
  allow_failure: true
  only:
    refs:
      - branches
  except:
    refs:
      - main
      - develop
    variables:
      - $REVIEW_DISABLED

# DEVELOP REVIEW
develop:
  <<: *dokku
  stage: review
  script:
    - export REVIEW_APP="$REVIEW_APPS_SUBDOMAIN_PREFIX-develop"
    - ssh dokku@$REVIEW_APPS_DOMAIN apps:create $REVIEW_APP 2> /dev/null || echo "App already exists"
    - ssh dokku@$REVIEW_APPS_DOMAIN certs:add $REVIEW_APP /home/dokku/.https/server.crt /home/dokku/.https/server.key
    - ssh dokku@$REVIEW_APPS_DOMAIN config:set $REVIEW_APP NODE_ENV=production
    - ssh dokku@$REVIEW_APPS_DOMAIN docker-options:add $REVIEW_APP build "--build-arg NODE_ENV=production"
    - git push dokku@$REVIEW_APPS_DOMAIN:$REVIEW_APP HEAD:refs/heads/main --force
    - echo $CI_ENVIRONMENT_URL > environment_url.txt
  environment:
    name: develop
    url: https://$REVIEW_APPS_SUBDOMAIN_PREFIX.$REVIEW_APPS_DOMAIN
    on_stop: stop develop
  artifacts:
    paths: [environment_url.txt]
  only:
    refs:
      - develop
  except:
    variables:
      - $REVIEW_DISABLED

stop develop:
  <<: *dokku
  stage: cleanup
  variables:
    GIT_STRATEGY: none
  script:
    - ssh dokku@$REVIEW_APPS_DOMAIN apps:destroy $REVIEW_APPS_SUBDOMAIN_PREFIX-develop --force
  environment:
    name: develop
    action: stop
  when: manual
  allow_failure: true
  only:
    refs:
      - develop
  except:
    variables:
      - $REVIEW_DISABLED

# STAGING REVIEW
staging:
  <<: *dokku
  stage: review
  script:
    - export REVIEW_APP="$REVIEW_APPS_SUBDOMAIN_PREFIX"
    - ssh dokku@$REVIEW_APPS_DOMAIN apps:create $REVIEW_APP 2> /dev/null || echo "App already exists"
    - ssh dokku@$REVIEW_APPS_DOMAIN certs:add $REVIEW_APP /home/dokku/.https/server.crt /home/dokku/.https/server.key
    - ssh dokku@$REVIEW_APPS_DOMAIN config:set $REVIEW_APP NODE_ENV=production
    - ssh dokku@$REVIEW_APPS_DOMAIN docker-options:add $REVIEW_APP build "--build-arg NODE_ENV=production"
    - git push dokku@$REVIEW_APPS_DOMAIN:$REVIEW_APP HEAD:refs/heads/main --force
    - echo $CI_ENVIRONMENT_URL > environment_url.txt
  environment:
    name: staging
    url: https://$REVIEW_APPS_SUBDOMAIN_PREFIX.$REVIEW_APPS_DOMAIN
    on_stop: stop staging
  artifacts:
    paths: [environment_url.txt]
  only:
    refs:
      - main
  except:
    variables:
      - $REVIEW_DISABLED

stop staging:
  <<: *dokku
  stage: cleanup
  variables:
    GIT_STRATEGY: none
  script:
    - ssh dokku@$REVIEW_APPS_DOMAIN apps:destroy $REVIEW_APPS_SUBDOMAIN_PREFIX --force
  environment:
    name: staging
    action: stop
  when: manual
  allow_failure: true
  only:
    refs:
      - main
  except:
    variables:
      - $REVIEW_DISABLED
