// Generado desde backend resources/llm/defensoria_extractor.yml (commit 013e86ea).
// Si el backend cambia la taxonomía, este archivo queda desincronizado.
// Ver docs/superpowers/plans/2026-07-31-recomendaciones-defensoria.md §9.
import type { SelectOption } from "@/types/select";

export const TAXONOMY: Record<string, string[]> = {
  "DERECHOS DE LAS PERSONAS CON DISCAPACIDAD": [
    "Accesibilidad y movilidad",
    "Certificados para personas con discapacidad (CUD)",
    "Cupo laboral, pequeños comercios y políticas de inclusión",
    "Curatela",
    "Exenciones y franquicias impositivas",
    "Gestión de elementos ortopédicos y prestaciones de salud (COPIDIS y Prog. Federal Incluir Salud)",
    "Pensiones no contributivas. Certificado médico oficial",
    "Reclamos de personas con CUD a obras sociales y empresas de medicina prepaga",
  ],
  "AMBIENTE y CAMBIO CLIMÁTICO": [
    "ACUMAR. Seguimiento de Plan Integral de Saneamiento",
    "Cambio climático. Energías renovables y eficiencia energética",
    "Cementerio de Autos",
    "Contaminación Sonora",
    "Contaminación con efluentes líquidos, emanaciones y olores nauseabundos",
    "Evaluación de Impacto y Seguro Ambiental",
    "Inundaciones",
    "Manejo de sustancias peligrosas",
    "Restauración ecológica y reservas",
    "Reciclado y recuperación de residuos domicialiarios",
    "Residuos peligrosos y patogénicos",
    "Ruidos molestos (fuente no difusa)",
    "Fauna urbana (silvestre y sinantrópica)",
    "Animales de compañía. Tenencia responsable y casos de maltrato",
    "Problemas con el Inst. Pasteur y atención veterinaria",
  ],
  COMUNICACIONES: [
    "Control de antenas",
    "Correo postal y encomiendas",
    "Reclamos colectivos en telecomunicaciones",
    "Incumplimientos y reclamos al ENACOM",
    "Internet, telefonía fija y televisión",
    "Plataformas de contenido",
    "Telefonía móvil",
  ],
  "EDUCACION, CULTURA, CIENCIA y TECNOLOGIA": [
    "Reclamos de centros de estudiantes y cooperadoras escolares",
    "Ciencia y tecnología",
    "Educación privada",
    "Educación estatal. Becas",
    "Educación estatal. Inscripciones y falta de vacantes",
    "Educación estatal. Infraestructura, mantenimiento y seguridad de escuelas",
    "Educación estatal. Falta de materiales e insumos",
    "Educación estatal. Comedores escolares y viandas",
    "Educación sexual integral",
    "Establecimientos de otras jurisdicciones",
    "Inclusión educativa",
    "Netbooks. Plan Sarmiento y Conectar igualdad",
    "Programas socioeducativos",
    "Situaciones de violencia, discriminación, convivencia y medidas disciplinarias",
    "Afectación de clases (extensión de jornada, suspensión, falta de cobertura de cargos)",
    "Títulos, pases, certificados y equivalencias",
    "Transporte escolar y boleto estudiantil",
    "Espacios culturales (bibliotecas, museos, centros culturales, teatros)",
    "Programas y actividades del Ministerio de Cultura",
  ],
  "DERECHOS LABORALES": [
    "Derechos laborales en el ámbito privado",
    "Violencia laboral en el ámbito privado",
    "Trabajo irregular y no registración",
    "Aportes previsionales y seguridad social",
    "Políticas de promoción del empleo y economía popular",
    "Seguridad, higiene y salud ocupacional en el ámbito privado",
    "Seguridad, higiene y salud ocupacional en el ámbito público",
    "Asignaciones familiares",
    "Seguro de desempleo",
    "Empleo público",
    "Violencia laboral en el ámbito público",
  ],
  "DEMOCRACIA, PARTICIPACIÓN y DESCENTRALIZACIÓN": [
    "Derechos políticos y procesos electorales",
    "Mecanismos de participación ciudadana e iniciativa parlamentaria",
    "Comunas, Consejos Consultivos y programas descentralizados",
  ],
  "DATOS PERSONALES y DERECHOS EN ENTORNOS DIGITALES": [
    "Dictámenes sobre actividad del Órgano Garante del Derecho de Acceso a la Información",
    "Registro de bases de datos personales",
    "Consultas sobre bases, tratamiento inadecuado de datos personales y derechos de sus titulares",
    "Políticas basadas en tecnologías digitales",
    "Vulneración de derechos en entornos digitales",
    "Violencia de género digital",
  ],
  "DEPORTES y RECREACIÓN": [
    "Colonias de vacaciones",
    "Deportes y discapacidad",
    "Infraestructura deportiva",
    "Polideportivos",
    "Eventos y actividades deportivas en vía pública",
    "Federaciones, clubes y gimnasios",
  ],
  "GENERO y DIVERSIDAD SEXUAL": [
    "Afectación de derechos de personas LGBTIQ+",
    "Inscripciones registrales igualitarias",
    "Documentación personal por identidad de género",
    "Explotación sexual, trata y prostitución",
    "Políticas públicas de igualdad de género",
    "Violencia de género",
  ],
  "POLÍTICAS DE INCLUSIÓN SOCIAL": [
    "Asignaciones universales",
    "Ciudadanía Porteña y Ticket Social",
    "Comedores comunitarios",
    "Pedidos de asistencia inmediata (bolsa de comida, leche, pañales, colchones)",
    "Programas del GCBA (Adolescencia, Nuestras Familias, FIT, Preasis)",
    "Programas del Gobierno Nacional (Tarjeta Alimentar, Progresar, Potenciar Trabajo)",
  ],
  "DERECHOS HUMANOS, ACCESO A LA JUSTICIA Y PROTECCIÓN CONTRA LA DISCRIMINACIÓN":
    [
      "Implementación de la Ley contra la Discriminación (Ley 5.261)",
      "Identidad biológica",
      "Difusión, promoción, asesoramiento e investigación sobre derechos humanos",
      "Patrocinio jurídico. Asesoramiento",
      "Políticas de derechos humanos y programas de subsidios y/o reparación",
      "Patrocinio jurídico. Audiencias y mediaciones",
      "Patrocinio jurídico. Causas Judiciales",
    ],
  "MEDIACIÓN, CONCILIACIÓN y ARBITRAJE": [
    "Gestión de conflictos vecinales",
    "Conciliaciones con autoridades gubernamentales u organismos públicos",
    "Mediaciones con empresas o instituciones privadas",
  ],
  "NIÑEZ, ADOLESCENCIA y JUVENTUD": [
    "Niñas/os y adolescentes en instituciones y situación de calle",
    "Niñas/os y adolescentes víctimas de violencia",
    "Acceso a derechos civiles y sociales de niñas/os y adolescentes",
    "Organizaciones juveniles",
    "Jóvenes con derechos vulnerados",
  ],
  "ORGANISMOS EXTERNOS": [
    "Renaper",
    "PAMI",
    "ANSES",
    "Ministerio Público de la Defensa",
  ],
  "DERECHOS DE LAS PERSONAS MIGRANTES": [
    "Procesos de ciudadanía",
    "Trámites y documentación migratoria",
    "Restricción a derechos por falta de documentación",
    "Diversidad cultural",
  ],
  "DERECHOS DE LAS PERSONAS MAYORES, JUBILADAS": [
    "Geriatricos y hogares. Solicitudes de internación, irregularidades y maltrato",
    "Jubilaciones, pensiones y retiros por invalidez",
    "PAMI. Atención médica y vacunación",
    "PAMI. Afiliación, cambio de cápita y reintegros",
    "PAMI. Medicamentos, protesis e insumos",
    "PAMI.Traslados, internaciones y cirugías",
    "PAMI. Subsidios y prestaciones (alimentaria, bolsón, social, sepelios, persona cuidadora)",
    "Programas alternativos a internación geriátrica (hogares de día, comedores, vivir en casa)",
    "Trámites y reclamos a ANSES",
  ],
  "VÍA PÚBLICA, TRÁNSITO y TRANSPORTE": [
    "Autopistas",
    "Bicicletas - bicisendas",
    "Alumbrado",
    "Aceras y calzadas",
    "Arbolado. Solicitud de corte de ramas y raíces",
    "Multas e infracciones de tránsito",
    "Obstáculos en vía pública (canteros, anclajes, postes, cableados)",
    "Semáforos y señalizaciones",
    "Colectivos, Ómnibus y METROBUS",
    "FFCC",
    "Reclamos a la CNRT",
    "Seguridad víal. Siniestros",
    "Subtes",
    "Tarifa social",
    "Tarjeta SUBE",
    "Taxis y remises",
    "Tránsito pesado",
  ],
  SALUD: [
    "Obras sociales. Altas, bajas, opción de cambio, co-pagos",
    "Obras sociales. Atención e internación domiciliaria. Cuidados paliativos",
    "Obras sociales. Demora en turnos",
    "Obras sociales. Problemas en guardias, tratamientos e internaciones",
    "Obras sociales. Maltrato y discriminación en la atención",
    "Obras sociales. Medicamentos, protesis e insumos",
    "Obras sociales. Prestaciones medicas en geriátricos",
    "Medicina prepaga. Altas, bajas, traspasos, co-pagos",
    "Medicina prepaga. Atención e internación domiciliaria. Cuidados paliativos",
    "Medicina prepaga. Demora en turnos",
    "Medicina prepaga. Problemas en guardias, tratamientos e internaciones",
    "Medicina prepaga. Maltrato y discriminación en la atención",
    "Medicina prepaga. Medicamentos, protesis e insumos",
    "Medicina prepaga. Prestaciones médicas en geriátricos",
    "Salud Pública. Atención e internación domiciliaria. Cuidados paliativos",
    "Salud Pública. Demora en turnos",
    "Salud Pública. Problemas en guardias, tratamientos e internaciones",
    "Salud Pública. Establecimientos sanitarios. Infraestructura y mantenimiento",
    "Salud Pública. Medicamentos, protesis e insumos",
    "Salud Pública. Maltrato y discriminación en la atención",
    "SAME",
    "Solicitud de historia clínica, confidencialidad y consentimiento informado",
    "Vacunación",
    "Hisopado y PCR",
    "Violencia obstétrica",
  ],
  "SALUD MENTAL": [
    "Activación del protocolo para situaciónes de crisis y  solicitudes de áreas temáticas",
    "Conflictos vecinales vinculados a la salud mental",
    "Salud mental. Problemas de atención, acceso, internación y tratamiento",
    "Intervención en situaciones de crisis y atención a personas damnificadas",
    "Adicciones. Problemas de atención, acceso, internación y tratamiento",
  ],
  "SERVICIOS PÚBLICOS": [
    "Agua y cloacas",
    "Agua y cloacas. Tarifa social y segmentación",
    "Cementerios",
    "Control de plagas",
    "Energía. EDENOR",
    "Energía. EDESUR",
    "Energía. Tarifa social y segmentación",
    "Estacionamiento medido",
    "Gas",
    "Gas. Tarifa social y segmentación",
    "Higiene urbana. Baldíos, predios o casas abandonadas",
    "Higiene urbana. Irregularidades en recolección de residuos domiciliarios",
    "Vehículos abandonados",
    "Verificación Técnica Vehicular (VTV)",
  ],
  TURISMO: [
    "Aeropuertos, puertos y terminales de micros",
    "Agencia de viajes. Pasajes, prestaciones y paquetes turísticos",
    "Agencia de viajes. Turismo estudiantil",
    "Alojamiento (reserva directa en hoteles y alquileres temporarios para turistas hasta 3 meses)",
    "Asistencia al viajero y seguros de cancelación",
    "Información y servicios a turistas",
    "Líneas áereas (compra y/o servicio directo)",
    "Medios de transporte (contratación directa de cruceros, bus turístico, alquiler de autos)",
    "Orientación a turista en trámites en migraciones, sanidad de fronteras, aduana, AFIP, RENAPER y consulados",
    "Orientación a turista varado en el país o en el extranjero",
    "Orientación a turista vinculado a delitos y/o contravenciones",
    "Previaje",
    "Turismo accesible y turismo social",
  ],
  "DERECHOS DE USUARIOS/AS, CONSUMIDORES/AS y ADMINISTRADOS/AS": [
    "Registro No Llame",
    "Automotores",
    "Medicina prepaga. Registro y condiciones de contratación",
    "Quejas contra la atención de la Dir. General de Defensa y Protección al Consumidor",
    "Reclamos ante la Administración Gubernamental de Ingresos Públicos (AGIP) - ABL, Ingresos Brutos, Patentes",
    "Reclamos por incumplimientos de proveedores en relaciones de consumo",
    "Servicios bancarios y financieros",
    "Trámite de documentación personal (DNI, partidas).",
    "Trámite de licencia de conducir",
  ],
  "DERECHOS URBANOS, ESPACIO PÚBLICO Y CONTROL COMUNAL": [
    "Riesgo de derrumbe",
    "Actividades comerciales e industriales. Permisos, habilitaciones y condiciones de funcionamiento",
    "Cartelería y publicidad en vía pública",
    "Concesiones",
    "Daños edilicios producidos por edificios públicos",
    "Edificios privados. Condiciones de seguridad",
    "Edificios públicos. Administración, mantenimiento y condiciones de seguridad",
    "Ferias",
    "Higiene y salud alimentaria",
    "Hoteles",
    "Locales bailables y discotecas",
    "Mala atención y demora en trámites ante organismos de gobierno y comunas",
    "Obras particulares",
    "Obras públicas",
    "Parques y plazas",
    "Patrimonio Público. Áreas de Protección Histórica y edificios catalogados",
    "Ocupación del espacio público",
    "Puestos de venta en la vía pública y venta ambulante",
    "Proveedores del Gobierno de la Ciudad de Buenos Aires. Legalidad de los contratos",
    "Proyectos urbanísticos",
    "Villas y asentamientos (planes de urbanización)",
  ],
  VIVIENDA: [
    "Personas residentes en Hoteles",
    "Complejos Habitacionales",
    "Créditos (Ley 341 a personas y cooperativas, Primera Casa, UVA)",
    "Inconvenientes con inmobiliarias",
    "Programas específicos (Ex AU3, Casa Amarilla, Ley 324, La Boca, Barrio Olímpico, Ley 624)",
    "Registro, inconvenitentes con administraciones de consorcio y expensas",
    "Problemas con el contrato de alquiler y vulneración de derechos de personas inquilinas",
    "Villas y asentamientos (viviendas, servicios, obras de emergencias y relocalizaciones)",
    "Desalojos",
    "Subsidio habitacional. Decreto 690/06 y 960/08",
    "Programas de apoyo habitacional. Decretos 1234/04, 97/05 y 574/09",
    "Hogares",
    "Situación de calle. Centros de Inclusión Social (ex paradores) y Programa Buenos Aires Presente (BAP)",
  ],
  "VIOLENCIA INSTITUCIONAL, PREVENCIÓN DE LA TORTURA y SEGURIDAD CIUDADANA": [
    "Condiciones de lugares de encierro",
    "Tortura y/o malos tratos en contexto de encierro",
    "Políticas y reclamos sobre seguridad ciudadana",
    "Violencia por las fuerzas de seguridad pública",
    "Corrupción de fuerzas de seguridad pública",
    "Violencia por personal de seguridad privada",
  ],
};

export const TEMA_OPTIONS: SelectOption[] = Object.keys(TAXONOMY).map(
  (tema) => ({
    id: tema,
    text: tema,
  }),
);

export function subtemaOptions(tema: string): SelectOption[] {
  const subtemas = TAXONOMY[tema];
  if (!subtemas) return [];
  return subtemas.map((subtema) => ({ id: subtema, text: subtema }));
}
